import type { AnalysisResponse, EvidenceBlock } from '@/types/api';

function evidence(overrides: Partial<EvidenceBlock> = {}): EvidenceBlock {
  return {
    meters: [
      {
        key: 'lm_predictability',
        label: 'Language-model predictability',
        strength: 0.91,
        level: 'high',
        value: 0.55,
        display: '55.0%',
        unit: 'fraction of tokens',
        reference: 'human training median 32.0%',
        detail: "Most words here were the reference model's own first choice.",
        available: true,
        value_level: 'well above',
        percentile_vs_human: 91,
      },
      {
        key: 'lexical_diversity',
        label: 'Lexical diversity',
        strength: 0.2,
        level: 'low',
        value: 3.1,
        display: '3.10',
        unit: 'root type-token ratio',
        reference: 'human training median 2.80',
        detail: 'Varied vocabulary for a sentence of this length.',
        available: true,
        value_level: 'above',
        percentile_vs_human: 80,
      },
    ],
    statements: [
      "Language-model predictability: 55.0% — well above the human training median (32.0%). Most words here were the reference model's own first choice. Signal strength: high.",
      "Perplexity is 14.2, substantially lower than the essay's own 31.8.",
    ],
    measurements: [
      {
        name: 'Perplexity',
        key: 'lm_perplexity',
        value: 14.2,
        unit: '14.2',
        reference: 'essay median 31.8',
        percentile_vs_human: 12,
        strength: null,
      },
    ],
    model_contributions: [
      {
        feature: 'agg_mean_lm_frac_top1',
        value: 0.55,
        standardised: 2.1,
        contribution: 0.42,
        direction: 'machine-like',
        method: 'linear',
      },
    ],
    engine_version: '1.0.0',
    ...overrides,
  };
}

export const SAMPLE_ANALYSIS: AnalysisResponse = {
  analysis_id: 'abc123def456',
  status: 'completed',
  classification: 'ai_polished',
  label: 'Potentially AI-polished',
  description:
    'The patterns are most consistent with human writing that has been edited or rewritten with machine assistance.',
  confidence: 'moderate',
  confidence_score: 0.71,
  probabilities: { human: 0.18, ai_generated: 0.11, ai_polished: 0.71 },
  margin: 0.53,
  abstained: false,
  abstain_reason: null,
  summary: {
    n_words: 240,
    n_characters: 1400,
    n_sentences: 4,
    n_paragraphs: 2,
    sentences_scored: 4,
    flagged_sentences: 2,
    uncertain_sentences: 1,
    human_like_sentences: 1,
    flagged_paragraphs: 1,
    uncertain_paragraphs: 0,
    flagged_share: 0.5,
    statistics: {
      mean_words_per_sentence: 17.4,
      sentence_length_std: 9.2,
      sentence_length_cv: 0.53,
      burstiness_index: -0.31,
      perplexity: 31.8,
      median_sentence_perplexity: 3.2,
      fraction_top1_tokens: 0.34,
      mean_token_logprob: -3.42,
      mean_token_entropy: 4.11,
      type_token_ratio: 0.62,
      root_type_token_ratio: 9.6,
      trigram_repeat_ratio: 0.012,
      pos_template_repeat_ratio: 0.08,
      max_style_shift: 1.15,
      style_changepoints: 1,
      flesch_reading_ease: 61.2,
      transition_word_rate: 1.8,
      contraction_rate: 0.4,
    },
    lm_tokens_scored: 320,
    lm_windows: 1,
    segmentation_backend: 'spacy',
  },
  paragraphs: [
    {
      paragraph_id: 0,
      start: 0,
      end: 60,
      n_sentences: 2,
      n_words: 20,
      score: 0.2,
      max_sentence_score: 0.3,
      human_likeness: 0.8,
      classification: 'likely_human',
      flagged_sentence_ids: [],
      uncertain_sentence_ids: [],
      sentence_ids: [0, 1],
    },
    {
      paragraph_id: 1,
      start: 62,
      end: 140,
      n_sentences: 2,
      n_words: 24,
      score: 0.78,
      max_sentence_score: 0.88,
      human_likeness: 0.22,
      classification: 'likely_ai_assisted',
      flagged_sentence_ids: [2, 3],
      uncertain_sentence_ids: [],
      sentence_ids: [2, 3],
    },
  ],
  sentences: [
    {
      sentence_id: 0,
      paragraph_id: 0,
      start: 0,
      end: 29,
      text: 'The robot never worked here.',
      score: 0.12,
      classification: 'likely_human',
      confidence: 'high',
      n_words: 5,
      features: { lm_perplexity: 42.1, sty_n_words: 5 },
    },
    {
      sentence_id: 1,
      paragraph_id: 0,
      start: 30,
      end: 60,
      text: 'It burned out twice that year.',
      score: 0.3,
      classification: 'likely_human',
      confidence: 'moderate',
      n_words: 6,
      features: { lm_perplexity: 38.4, sty_n_words: 6 },
    },
    {
      sentence_id: 2,
      paragraph_id: 1,
      start: 62,
      end: 110,
      text: 'Through this transformative journey, I discovered much.',
      score: 0.88,
      classification: 'likely_ai_assisted',
      confidence: 'high',
      n_words: 7,
      features: { lm_perplexity: 14.2, sty_n_words: 7 },
      evidence: evidence(),
    },
    {
      sentence_id: 3,
      paragraph_id: 1,
      start: 111,
      end: 140,
      text: 'Moreover, it instilled resolve.',
      score: 0.68,
      classification: 'possibly_ai_assisted',
      confidence: 'moderate',
      n_words: 4,
      features: { lm_perplexity: 18.9, sty_n_words: 4 },
      evidence: evidence({ statements: ['Formal connective density is elevated.'] }),
    },
  ],
  evidence: evidence({
    statements: [
      'Sentence-length uniformity is elevated (0.53 coefficient of variation).',
      'The phrase "transformative journey" appears 2 times.',
    ],
  }),
  rhythm: [
    { index: 0, paragraph_index: 0, words: 5, deviation_from_mean: -0.5, abs_diff_prev: 0, clauses: 1, mean_logprob: -3.9, perplexity: 42.1 },
    { index: 1, paragraph_index: 0, words: 6, deviation_from_mean: 0.5, abs_diff_prev: 1, clauses: 1, mean_logprob: -3.7, perplexity: 38.4 },
    { index: 2, paragraph_index: 1, words: 7, deviation_from_mean: 1.5, abs_diff_prev: 1, clauses: 2, mean_logprob: -2.6, perplexity: 14.2 },
    { index: 3, paragraph_index: 1, words: 4, deviation_from_mean: -1.5, abs_diff_prev: 3, clauses: 1, mean_logprob: -2.9, perplexity: 18.9 },
  ],
  repetition: {
    repeated_phrases: [
      { phrase: 'transformative journey', length: 2, count: 2, sentence_indices: [2] },
    ],
    repeated_syntactic_templates: [
      { template: 'PRON VERB DET NOUN', sentence_count: 3, sentence_indices: [0, 1, 3] },
    ],
  },
  model: {
    detector_version: '1.0.0',
    model_version: '1.0.0',
    dataset_version: '1.0.0',
    features_version: '1.0.0',
    explanation_engine_version: '1.0.0',
    data_regime: 'bootstrap',
    language_model: 'distilgpt2',
    language_model_role: 'instrument for token probabilities; it does not classify the essay',
    classifier: 'hybrid::random_forest',
    trained_at: '2026-08-14T23:00:00Z',
  },
  timings: { total_ms: 412 },
  content_hash: 'deadbeef',
  created_at: '2026-08-14T23:10:00Z',
  persisted: false,
  cached: false,
  warnings: [],
  disclaimer:
    'AI detection is probabilistic. A flag is evidence for human review, not proof of authorship.',
};

export const SAMPLE_HEALTH = {
  status: 'ok' as const,
  version: '1.0.0',
  environment: 'development',
  components: [
    { name: 'mongodb', enabled: true, available: true, detail: 'database=ai_essay_detector' },
    { name: 'detector_model', enabled: true, available: true, detail: 'model_version=1.0.0' },
  ],
  detector: {},
  uptime_seconds: 12.5,
  checked_at: '2026-08-14T23:10:00Z',
};

export const SAMPLE_PRIVACY = {
  save_essays_default: false,
  per_request_override_supported: true,
  retention_days: 30,
  what_is_stored: ['analysis id'],
  what_is_never_stored: ['the essay text'],
  what_is_never_logged: ['the essay text'],
  deletion_endpoint: 'DELETE /api/v1/analysis/{analysis_id}',
};
